import assert from 'node:assert/strict';
import './setup-xml-provider.mjs';
import { inspectDocumentParts, applyRedlineToOxml } from '../index.js';
import { applyOperationsToDocumentXml } from '../services/standalone-operation-runner.js';

// Regression: Markdown bullets generated by a redline must not reuse w:num / w:abstractNum IDs
// that already exist in the supplied source numbering part.

const W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"';
const numberingXml = `<w:numbering ${W}>`
    + '<w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum>'
    + '<w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num></w:numbering>';
const documentXml = `<w:document ${W}><w:body>`
    + '<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>Existing numbered item.</w:t></w:r></w:p>'
    + '<w:p><w:r><w:t>Plain provision.</w:t></w:r></w:p>'
    + '<w:sectPr/></w:body></w:document>';

function bulletNumIds(xml) {
    return [...xml.matchAll(/<w:p\b(?:(?!<\/w:p>)[\s\S])*?<w:numId w:val="(\d+)"\/>(?:(?!<\/w:p>)[\s\S])*?(First|Second) bullet/g)].map(m => m[1]);
}

function assertFreshBullet(label, docXml, generatedNumbering) {
    const ids = bulletNumIds(docXml);
    assert.equal(ids.length, 2, `${label}: two bullet paragraphs found`);
    assert.equal(new Set(ids).size, 1, `${label}: bullets share one list`);
    assert.notEqual(ids[0], '1', `${label}: bullets must not reuse existing numId 1`);
    const num = new RegExp(String.raw`<w:num\b[^>]*w:numId="${ids[0]}"[^>]*>\s*<w:abstractNumId w:val="(\d+)"`).exec(generatedNumbering);
    assert.ok(num, `${label}: generated numbering defines numId ${ids[0]}`);
    assert.notEqual(num[1], '0', `${label}: abstractNum must not collide with existing 0`);
    const abs = new RegExp(String.raw`<w:abstractNum\b[^>]*w:abstractNumId="${num[1]}"[\s\S]*?</w:abstractNum>`).exec(generatedNumbering);
    assert.ok(abs, `${label}: abstractNum ${num[1]} defined`);
    assert.match(abs[0], /<w:lvl\b[^>]*w:ilvl="0"[\s\S]*?<w:numFmt w:val="bullet"/, `${label}: level 0 is bullet`);
}

const target = inspectDocumentParts({ documentXml, numberingXml }).paragraphs[1];
const operation = {
    type: 'redline',
    target: { index: 2, exactText: target.exactText, paragraphId: target.paragraphId, fingerprint: target.fingerprint },
    modified: 'Rewritten provision:\n- First bullet.\n- Second bullet.',
    structuredContent: true
};
const runnerOptions = { atomic: true, generateRedlines: true, structuredContent: true };

// 1. Standalone runner with only numberingXml supplied.
{
    const result = await applyOperationsToDocumentXml(documentXml, [operation], 'Tester', { numberingXml }, runnerOptions);
    assert.equal(result.status, 'ok');
    assert.ok(result.numberingXmlParts.length > 0, 'runner emits numbering part');
    assertFreshBullet('runner', result.documentXml, result.numberingXmlParts.join('\n'));
    assert.match(result.documentXml, /<w:numId w:val="1"\/>[\s\S]*Existing numbered item/, 'source list keeps numId 1');
}

// 2. applyRedlineToOxml direct list generation with numbering supplied.
{
    const para = '<w:p><w:r><w:t>Plain provision.</w:t></w:r></w:p>';
    const pkg = `<pkg:package xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage"><pkg:part pkg:name="/word/document.xml"><pkg:xmlData><w:document ${W}><w:body>${para}</w:body></w:document></pkg:xmlData></pkg:part></pkg:package>`;
    const result = await applyRedlineToOxml(pkg, 'Plain provision.', 'Rewritten provision:\n- First bullet.\n- Second bullet.', {
        author: 'Tester', generateRedlines: true, structuredContent: true, numberingXml
    });
    assert.ok(result.hasChanges);
    const docXml = result.oxml;
    const ids = bulletNumIds(docXml);
    assert.equal(ids.length, 2);
    assertFreshBullet('applyRedlineToOxml', docXml, docXml.slice(docXml.indexOf('/word/numbering.xml')));
}


// 3. openDocx facade: merged numbering part keeps the original definitions and adds a fresh bullet one.
{
    const { readFileSync } = await import('node:fs');
    const { openDocx } = await import('../index.js');
    const { unzipDocx } = await import('../document/zip-archive.js');
    const sourceBytes = new Uint8Array(readFileSync(new URL('./fixtures/agentic-lists/nested-lists-source.docx', import.meta.url)));
    const decoder = new TextDecoder();
    const partOf = (bytes, name) => decoder.decode(unzipDocx(bytes).get(name));
    const sourceNumbering = partOf(sourceBytes, 'word/numbering.xml');
    const doc = await openDocx(sourceBytes);
    const result = await doc.applyOperations([{
        type: 'redline',
        target: { index: 1, exactText: partOf(sourceBytes, 'word/document.xml').match(/<w:t[^>]*>([^<]+)<\/w:t>/)[1] },
        modified: 'Intro line\n- First bullet.\n- Second bullet.',
        structuredContent: true
    }], { author: 'Tester', atomic: true, structuredContent: true, generateRedlines: true });
    assert.equal(result.status, 'ok');
    const outNumbering = partOf(result.uint8Array, 'word/numbering.xml');
    const outDoc = partOf(result.uint8Array, 'word/document.xml');
    const sourceNumIds = [...sourceNumbering.matchAll(/<w:num\b[^>]*w:numId="(\d+)"/g)].map(m => m[1]);
    const ids = bulletNumIds(outDoc);
    assert.equal(ids.length, 2);
    assert.ok(!sourceNumIds.includes(ids[0]), 'facade: bullets use a fresh numId');
    for (const id of sourceNumIds) assert.ok(outNumbering.includes(`w:numId="${id}"`), `facade: source numId ${id} preserved`);
    assertFreshBullet('facade', outDoc, outNumbering);
}

console.log('generated_bullet_numbering_collision_tests: facade ok');
